# Generated by Django 3.2.2 on 2021-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default='0', max_length=50)),
                ('lng', models.FloatField(default='0', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('category', models.CharField(default='none', max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
